Update pr-auto-approve.yml

diff --git a/.github/workflows/pr-auto-approve.yml b/.github/workflows/pr-auto-approve.yml
--- a/.github/workflows/pr-auto-approve.yml
+++ b/.github/workflows/pr-auto-approve.yml
@@ -14,6 +14,31 @@ jobs:
     if: ${{ contains(github.event.pull_request.labels.*.name, 'Auto Approve') }}
     
     steps:
+    
+      - name: Check for changed files that are probably public API
+        id: public-api-changes
+        uses: tj-actions/changed-files@v35
+        with:
+          files: |
+            app/app_pb/**
+            contrib/**/include/**
+            contrib/ecaltime/ecaltime_pb/**
+            ecal/core/cfg/**
+            ecal/core/include/**
+            ecal/core_pb/**
+            ecal/pb/**
+            lang/**
+            thirdparty/**
+            .gitmodules
+            
+      - name: Public API has changed?
+        if: steps.public-api-changes.outputs.any_changed == 'true'
+        run: |
+          echo "ERROR: Public API has changed:"
+          echo "${{ steps.changed-files-excluded.outputs.all_changed_files }}"
+          exit 1
+            
       - uses: hmarr/auto-approve-action@v3
+        if: steps.public-api-changes.outputs.any_changed == 'false'
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
